export const TOPICS = [
  { id: "T01", order: 1, title: "O QUE É AFASIA?", authors: "Aniela Improta França" },
  { id: "T02", order: 2, title: "É POSSÍVEL TRADUZIR UM TEXTO DE QUALQUER LÍNGUA PARA QUALQUER LÍNGUA?", authors: "Caetano W. Galindo" },
  { id: "T03", order: 3, title: "POR QUE AS LÍNGUAS MUDAM?", authors: "Carlos Alberto Faraco" },
  { id: "T04", order: 4, title: "O QUE É UM TEXTO?", authors: "Carmem Luci da Costa Silva" },
  { id: "T05", order: 5, title: "COMO AS PALAVRAS MUDAM DE SENTIDO?", authors: "Celso Ferrarezi Jr." },
  { id: "T06", order: 6, title: "O QUE É SOTAQUE?", authors: "Christina Abreu Gomes" },
  { id: "T07", order: 7, title: "QUANTAS LÍNGUAS SÃO FALADAS HOJE NO MUNDO?", authors: "Cléo Altenhofen" },
  { id: "T08", order: 8, title: "POR QUE FALAMOS PORTUGUÊS NO BRASIL?", authors: "Dante Lucchesi" },
  { id: "T09", order: 9, title: "QUAL É A RELAÇÃO ENTRE AS LÍNGUAS E AS SOCIEDADES?", authors: "Dermeval da Hora" },
  { id: "T10", order: 10, title: "TODAS AS SOCIEDADES HUMANAS POSSUEM UMA LÍNGUA?", authors: "Eduardo Kenedy" },
  { id: "T11", order: 11, title: "QUAL É A RELAÇÃO ENTRE O CÉREBRO E A LINGUAGEM?", authors: "Edwiges Maria Morato" },
  { id: "T12", order: 12, title: "O QUE É A NORMA-PADRÃO?", authors: "Elisa Battisti" },
  { id: "T13", order: 13, title: "COMO NASCEM E MORREM AS LÍNGUAS?", authors: "Esmeralda Vailati Negrão" },
  { id: "T14", order: 14, title: "EXISTE UMA LÍNGUA MAIS DIFÍCIL DO QUE OUTRA?", authors: "Evani Viotti e Juliana Ángel-Osorno" },
  { id: "T15", order: 15, title: "O QUE É UM DICIONÁRIO?", authors: "Félix Bugueño Miranda" },
  { id: "T16", order: 16, title: "POR QUE AS LÍNGUAS SÃO DIFERENTES?", authors: "Giulia Bossaglia" },
  { id: "T17", order: 17, title: "O QUE SÃO METÁFORAS?", authors: "Heronides Moura" },
  { id: "T18", order: 18, title: "QUAL É A MELHOR IDADE PARA APRENDERMOS UMA SEGUNDA LÍNGUA?", authors: "Ingrid Finger" },
  { id: "T19", order: 19, title: "O QUE SÃO DIALETOS?", authors: "Izete Lehmkuhl Coelho" },
  { id: "T20", order: 20, title: "COMO APRENDEMOS UMA LÍNGUA ESTRANGEIRA?", authors: "Janaina Weissheimer" },
  { id: "T21", order: 21, title: "COMO SÃO CRIADAS AS PALAVRAS NOVAS DE UMA LÍNGUA?", authors: "João Paulo Lazzarini Cyrino" },
  { id: "T22", order: 22, title: "QUAL É A FUNÇÃO DA LINGUAGEM?", authors: "José Luiz Fiorin" },
  { id: "T23", order: 23, title: "QUAL É A RELAÇÃO ENTRE O COMPUTADOR E A LINGUAGEM?", authors: "Leonel Figueiredo de Alencar" },
  { id: "T24", order: 24, title: "O QUE É A ESCRITA?", authors: "Lourenço Chacon" },
  { id: "T25", order: 25, title: "O QUE É EDUCAÇÃO BILÍNGUE?", authors: "Luciana de Souza Brentano" },
  { id: "T26", order: 26, title: "OS ANIMAIS TÊM LINGUAGEM?", authors: "Luciana Raccanello Storto" },
  { id: "T27", order: 27, title: "A FALA É DIFERENTE DA ESCRITA?", authors: "Luiz Carlos Cagliari" },
  { id: "T28", order: 28, title: "O QUE É DISLEXIA?", authors: "Mailce Borges Mota" },
  { id: "T29", order: 29, title: "O QUE É UMA LÍNGUA ARTIFICIAL?", authors: "Marcelo Ferreira" },
  { id: "T30", order: 30, title: "AS REFORMAS ORTOGRÁFICAS SÃO NECESSÁRIAS?", authors: "Marcos Bagno" },
  { id: "T31", order: 31, title: "COMO FUNCIONA UM TRADUTOR AUTOMÁTICO?", authors: "Marcos Lopes" },
  { id: "T32", order: 32, title: "QUANTAS LÍNGUAS SÃO FALADAS HOJE NO BRASIL?", authors: "Margarida Petter" },
  { id: "T33", order: 33, title: "COMO SE DÁ A AQUISIÇÃO DA LINGUAGEM ESCRITA?", authors: "Maria Bernadete Marques Abaurre" },
  { id: "T34", order: 34, title: "O PORTUGUÊS BRASILEIRO É UMA LÍNGUA DIFERENTE DO PORTUGUÊS EUROPEU?", authors: "Maria Eugenia Lammoglia Duarte" },
  { id: "T35", order: 35, title: "QUAL É A RELAÇÃO ENTRE INCONSCIENTE E LINGUAGEM?", authors: "Maria Francisca Lier-DeVitto" },
  { id: "T36", order: 36, title: "O QUE É LEITURA?", authors: "Mariangela Rios de Oliveira" },
  { id: "T37", order: 37, title: "QUAL É A RELAÇÃO ENTRE PENSAMENTO E LINGUAGEM?", authors: "Marianne Carvalho Bezerra Cavalcante" },
  { id: "T38", order: 38, title: "O QUE É PRECONCEITO LINGUÍSTICO?", authors: "Maria Marta Pereira Scherre" },
  { id: "T39", order: 39, title: "O QUE É UMA LÍNGUA?", authors: "Maximiliano Guimarães" },
  { id: "T40", order: 40, title: "O QUE É ENTONAÇÃO?", authors: "Miguel Oliveira Jr." },
  { id: "T41", order: 41, title: "O QUE É RECONHECIMENTO DE VOZ?", authors: "Plínio A. Barbosa" },
  { id: "T42", order: 42, title: "O QUE É UMA PALAVRA?", authors: "Rafael Dias Minussi" },
  { id: "T43", order: 43, title: "O QUE É UMA LÍNGUA MORTA?", authors: "Renato Miguel Basso" },
  { id: "T44", order: 44, title: "O QUE É UMA LÍNGUA DE SINAIS?", authors: "Ronice Müller de Quadros" },
  { id: "T45", order: 45, title: "COMO ADQUIRIMOS NOSSA LÍNGUA MATERNA?", authors: "Ruth Lopes" },
  { id: "T46", order: 46, title: "O QUE É GRAMÁTICA?", authors: "Sergio de Moura Menuzzi e Gabriel de Ávila Othero" },
  { id: "T47", order: 47, title: "O QUE É UM ESTRANGEIRISMO?", authors: "Sírio Possenti" },
  { id: "T48", order: 48, title: "É POSSÍVEL CLASSIFICAR AS LÍNGUAS?", authors: "Thomas Daniel Finbow" },
  { id: "T49", order: 49, title: "É MAIS DIFÍCIL APRENDER UMA LÍNGUA DEPOIS DE ADULTO?", authors: "Ubiratã Kickhöfel Alves" },
  { id: "T50", order: 50, title: "AS MULHERES FALAM DIFERENTE DOS HOMENS?", authors: "Valquíria Claudete Machado Borba e Samuel Gomes de Oliveira" },
  { id: "T51", order: 51, title: "COMO SURGIU A LINGUAGEM?", authors: "Vitor A. Nóbrega" }
];

export const TOPIC_MAP = Object.fromEntries(TOPICS.map(topic => [topic.id, topic]));
